CREATE TABLE IF NOT EXISTS books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  genres JSON NOT NULL,
  is_read TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS challenge (
  id INT AUTO_INCREMENT PRIMARY KEY,
  goal INT NOT NULL,
  year INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS challenge_books (
  challenge_id INT NOT NULL,
  book_id INT NOT NULL,
  PRIMARY KEY (challenge_id, book_id),
  FOREIGN KEY (challenge_id) REFERENCES challenge(id) ON DELETE CASCADE,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS currently_reading (
  id INT AUTO_INCREMENT PRIMARY KEY,
  book_id INT NOT NULL UNIQUE,
  current_page INT NOT NULL DEFAULT 0,
  started_at DATE NOT NULL DEFAULT (CURRENT_DATE),
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reading_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  book_id INT NOT NULL,
  pages_read INT NOT NULL,
  log_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);
