export const fixture = {
  books: [
    {
      id: 1,
      title: "L’Écume des jours",
      author: "Boris Vian",
      genres: ["Roman", "Classique"],
      is_read: false,
      is_wishlist: false,
      is_gift: false,
      page_count: 320,
      color: "#395b56",
      year: 2025,
      rating: null,
      size: 3,
    },
    {
      id: 2,
      title: "Dune",
      author: "Frank Herbert",
      genres: ["Science-fiction"],
      is_read: true,
      is_wishlist: false,
      is_gift: true,
      page_count: 640,
      color: "#a2663d",
      year: null,
      rating: 5,
      size: 3,
    },
    {
      id: 3,
      title: "La Vie devant soi",
      author: "Romain Gary",
      genres: ["Roman"],
      is_read: false,
      is_wishlist: false,
      is_gift: false,
      page_count: 280,
      color: "#884a43",
      year: 2024,
      rating: null,
      size: 2,
    },
    {
      id: 4,
      title: "Une chambre à soi",
      author: "Virginia Woolf",
      genres: ["Essai"],
      is_read: false,
      is_wishlist: true,
      is_gift: false,
      page_count: 176,
      color: "#665574",
      year: null,
      rating: null,
      size: 2,
    },
    {
      id: 5,
      title: "Les Villes invisibles",
      author: "Italo Calvino",
      genres: ["Roman"],
      is_read: false,
      is_wishlist: false,
      is_gift: false,
      page_count: 208,
      color: "#5e674c",
      year: 2025,
      rating: 4,
      size: 2,
    },
    {
      id: 6,
      title: "L’Usage du monde",
      author: "Nicolas Bouvier",
      genres: ["Voyage"],
      is_read: true,
      is_wishlist: false,
      is_gift: false,
      page_count: 384,
      color: "#43566e",
      year: 2024,
      rating: 5,
      size: 3,
    },
  ],
  current: [
    {
      id: 1,
      book_id: 1,
      title: "L’Écume des jours",
      author: "Boris Vian",
      genres: ["Roman"],
      page_count: 320,
      current_page: 112,
      started_at: "2026-09-01",
      color: "#395b56",
    },
  ],
  loans: [
    {
      id: 1,
      book_id: 3,
      person: "Camille",
      loan_date: "2026-08-20",
      returned_date: null,
      title: "La Vie devant soi",
      author: "Romain Gary",
    },
  ],
  challenge: { id: 1, year: 2026, goal: 12, books: [] },
  log: [
    {
      log_date: "2026-09-08",
      pages: 32,
      books: [{ title: "L’Écume des jours", pages: 32 }],
    },
  ],
};
fixture.challenge.books = [fixture.books[0], fixture.books[1]];
