<?php
require_once __DIR__ . '/config.php';

// Vérifier que la table est vide
$count = $pdo->query('SELECT COUNT(*) FROM books')->fetchColumn();
if ($count > 0) {
    echo json_encode(['error' => "La table contient déjà $count livres. Seed annulé."]);
    exit;
}

$books = [
    ["Kallocaïne", "Karin Boye", ["Dystopie", "Science-fiction", "Anticipation"]],
    ["Après le monde", "Antoinette Rychner", ["Post-apocalyptique", "Dystopie", "Écoféministe", "Collapsologie"]],
    ["Dans la forêt", "Jean Hegland", ["Post-apocalyptique", "Nature writing", "Roman d'apprentissage", "Survie"]],
    ["Ubik", "Philip K. Dick", ["Science-fiction", "Dystopie", "Philosophique", "Paranormal"]],
    ["2054", "Elliot Ackerman", ["Thriller", "Anticipation", "Géopolitique", "Science-fiction"]],
    ["Lux", "Maxime Chattam", ["Thriller", "Anticipation", "Post-apocalyptique", "Science-fiction"]],
    ["Le gang de la clef à molette", "Edward Abbey", ["Roman", "Écologie", "Aventure", "Satire"]],
    ["Sans âme", "Charlotte Heuse", ["Roman", "Fantastique", "Drame"]],
    ["Babel", "R.F. Kuang", ["Fantasy", "Historique", "Dark Academia", "Politique"]],
    ["Le Temps des sorcières", "Alix E. Harrow", ["Fantasy", "Féministe", "Historique", "Surnaturel"]],
    ["Celle qui devint le soleil", "Shelley Parker-Chan", ["Fantasy", "Historique", "Chine", "Épique"]],
    ["Un monde après l'autre", "Jodi Taylor", ["Science-fiction", "Voyage dans le temps", "Humour", "Aventure"]],
    ["Jane Eyre", "Charlotte Brontë", ["Classique", "Romance", "Gothique", "Victorien"]],
    ["Furies", "Julie Ruocco", ["Thriller", "Polar", "Psychologique"]],
    ["Camille, 1815", "Armand Clery", ["Historique", "Roman", "France"]],
    ["Le Roi et l'horloger", "Arnaldur Indriðason", ["Polar", "Islandais", "Mystère", "Crime"]],
    ["La Couturière de Dachau", "Mary Chamberlain", ["Historique", "Seconde Guerre mondiale", "Drame", "Biographique"]],
    ["Le non de Klara", "Soazig Aaron", ["Roman", "Féministe", "Contemporain", "Psychologique"]],
    ["Le Grand Feu", "Léonor de Récondo", ["Roman", "Historique", "Drame", "Littéraire"]],
    ["Mendelssohn est sur le toit", "Jiří Weil", ["Historique", "Seconde Guerre mondiale", "Roman tchèque", "Satire"]],
    ["Les Passeurs de livres de Daraya", "Delphine Minoui", ["Documentaire", "Guerre", "Syrie", "Témoignage"]],
    ["Jeanne Seymour : La Reine bien-aimée", "Alison Weir", ["Historique", "Biographie", "Tudor", "Romance"]],
    ["Madame Pylinska et le secret de Chopin", "Éric-Emmanuel Schmitt", ["Roman", "Musique", "Philosophique", "Littéraire"]],
    ["La Librairie des chats noirs", "Piergiorgio Pulixi", ["Polar", "Italien", "Mystère", "Thriller"]],
    ["L'Empreinte", "Alexandria Marzano-Lesnevich", ["True Crime", "Mémoire", "Justice", "Documentaire"]],
    ["Rouge Karma", "Jean-Christophe Grangé", ["Thriller", "Polar", "Mystique", "Action"]],
    ["Metropolis", "Philip Kerr", ["Polar historique", "Berlin", "Noir", "Crime"]],
    ["Nous étions le sel de la mer", "Roxanne Bouchard", ["Roman québécois", "Drame", "Maritime", "Psychologique"]],
    ["Le mari parfait d'Agatha Christie", "Bénédicte Jourgeaud", ["Biographie romancée", "Historique", "Mystère", "Littéraire"]],
    ["Le Maître des énigmes", "Danielle Trussoni", ["Thriller", "Mystère", "Aventure", "Ésotérique"]],
    ["Le Dernier inventeur", "Héloïse Guay de Bellissen", ["Roman", "Historique", "Science", "Aventure"]],
    ["Là où chantent les écrevisses", "Delia Owens", ["Roman", "Nature writing", "Mystère", "Coming-of-age"]],
    ["Cinq coeurs en sursis", "Laure Manel", ["Romance", "Contemporain", "Feel-good", "Drame"]],
    ["Petites boîtes", "Yōko Ogawa", ["Roman japonais", "Littéraire", "Mélancolique", "Poétique"]],
    ["Qu'importe la couleur du ciel", "Valérie Cohen", ["Roman", "Contemporain", "Drame", "Psychologique"]],
    ["La vérité sur la lumière", "Auður Ava Ólafsdóttir", ["Roman islandais", "Littéraire", "Poétique", "Nature"]],
    ["Noël surprise dans les Highlands", "Sarah Morgan", ["Romance", "Noël", "Feel-good", "Écossais"]],
    ["Rhapsodie balkanique", "Maria Kassimova-Moisset", ["Roman", "Balkans", "Historique", "Culturel"]],
    ["La vie avant l'homme", "Margaret Atwood", ["Roman", "Psychologique", "Canadien", "Féministe"]],
    ["Le Prince à la petite tasse", "Emilie de Turckheim", ["Roman", "Conte moderne", "Fantaisie", "Humour"]],
    ["Bimbo: Repenser les normes de la féminité", "Edie Blanchard", ["Essai", "Féminisme", "Sociologie", "Culture populaire"]],
    ["Psychogénéalogie", "Anne Ancelin Schützenberger", ["Psychologie", "Thérapie", "Famille", "Développement personnel"]],
    ["Nous sommes tous des féministes", "Chimamanda Ngozi Adichie", ["Essai", "Féminisme", "Société", "Manifeste"]],
    ["Ni vues ni connues", "Collectif Georgette Sand", ["Histoire", "Féminisme", "Biographies", "Société"]],
    ["Histoire des préjugés", "Jeanne Guérout", ["Histoire", "Sociologie", "Essai", "Culture"]],
    ["Le livre des haïku", "Jack Kerouac", ["Poésie", "Haïku", "Beat Generation", "Zen"]],
    ["The Best of Europe for Women", "Choisir la cause des femmes", ["Essai", "Féminisme", "Europe", "Politique"]],
    ["Les grandes oubliées", "Titiou Lecoq", ["Histoire", "Féminisme", "Biographies", "Essai"]],
    ["Le deuxième sexe, I", "Simone de Beauvoir", ["Philosophie", "Féminisme", "Essai", "Classique"]],
    ["Ces hommes qui m'expliquent la vie", "Rebecca Solnit", ["Essai", "Féminisme", "Société", "Culture"]],
    ["Pourquoi les Kevin ne deviennent pas médecins", "Étienne Guertin-Tardif", ["Sociologie", "Essai", "Société", "Québécois"]],
    ["Né d'aucune femme", "Franck Bouysse", ["Roman", "Noir", "Rural", "Drame"]],
    ["Les Hauts de Hurlevent", "Emily Brontë", ["Classique", "Gothique", "Romance", "Victorien"]],
    ["L'Île au trésor", "Robert Louis Stevenson", ["Aventure", "Classique", "Pirates", "Jeunesse"]],
    ["Le coût de la virilité", "Lucile Peytavin", ["Essai", "Sociologie", "Féminisme", "Économie"]],
    ["Clytemnestra", "Costanza Casati", ["Mythologie", "Historique", "Féministe", "Grèce antique"]],
    ["Moi qui n'ai pas connu les hommes", "Jacqueline Harpman", ["Science-fiction", "Dystopie", "Féministe", "Philosophique"]],
    ["Ariadne", "Jennifer Saint", ["Mythologie", "Fantasy", "Féministe", "Grèce antique"]],
    ["La brillante destinée d'Elizabeth Zott", "Bonnie Garmus", ["Roman", "Féministe", "Humour", "Années 60"]],
    ["Dry", "Neal Shusterman", ["Young Adult", "Dystopie", "Survie", "Écologie"]],
    ["La Reine du noir", "Julia Bartz", ["Thriller", "Mystère", "Psychologique", "Huis clos"]],
    ["Sublime Royaume", "Yaa Gyasi", ["Roman", "Famille", "Ghana", "Diaspora"]],
    ["American Gods", "Neil Gaiman", ["Fantasy", "Mythologie", "Urban Fantasy", "Épique"]],
    ["Les Pirates de Dieu", "François-Henri Soulié", ["Historique", "Aventure", "Maritime", "Religion"]],
    ["Les Contemplées", "Pauline Hillier", ["Roman", "Féministe", "Contemporain", "Philosophique"]],
    ["La prophétesse voilée", "Jean d'Aillon", ["Historique", "Mystère", "France", "17e siècle"]],
    ["Le Soleil des Scorta", "Laurent Gaudé", ["Roman", "Saga familiale", "Italie", "Drame"]],
    ["Kim Jiyoung, Born 1982", "Cho Nam-Joo", ["Roman coréen", "Féministe", "Société", "Contemporain"]],
    ["Les Naufragés du Wager", "David Grann", ["Histoire", "Maritime", "Aventure", "Survie"]],
    ["Perspective", "Laurent Binet", ["Roman", "Historique", "Art", "Renaissance"]],
    ["Les Hirondelles de Kaboul", "Yasmina Khadra", ["Roman", "Afghanistan", "Guerre", "Drame"]],
    ["Les sorcières de Vardø", "Anya Bergman", ["Historique", "Sorcellerie", "Norvège", "Féministe"]],
    ["L'Île des âmes", "Piergiorgio Pulixi", ["Thriller", "Noir", "Sardaigne", "Mystère"]],
    ["La Septième Lune", "Piergiorgio Pulixi", ["Thriller", "Noir", "Italien", "Mystère"]],
    ["Lucia", "Bernard Minier", ["Thriller", "Polar", "Psychologique", "Suspense"]],
    ["Les Graciées", "Kiran Millwood Hargrave", ["Historique", "Féministe", "Sorcellerie", "17e siècle"]],
    ["Les Jardins de Zagarand", "Eric de Kermel", ["Roman", "Orient", "Spirituel", "Philosophique"]],
    ["Women and Other Monsters", "Jess Zimmerman", ["Essai", "Mythologie", "Féminisme", "Culture"]],
    ["L'Énigme de Turnglass", "Gareth Rubin", ["Mystère", "Historique", "Victorien", "Thriller"]],
    ["Off With Her Head", "Eleanor Herman", ["Histoire", "Féminisme", "Biographies", "Pouvoir"]],
    ["La Parabole des talents", "Octavia E. Butler", ["Science-fiction", "Dystopie", "Afrofuturisme", "Post-apocalyptique"]],
    ["La Parabole du semeur", "Octavia E. Butler", ["Science-fiction", "Dystopie", "Afrofuturisme", "Post-apocalyptique"]],
    ["Beauté fatale", "Mona Chollet", ["Essai", "Féminisme", "Sociologie", "Beauté"]],
    ["Les Dieux du tango", "Carolina De Robertis", ["Roman", "Historique", "Argentine", "LGBTQ+"]],
    ["Noir comme la mer", "Mary Higgins Clark", ["Thriller", "Suspense", "Mystère", "Crime"]],
    ["Le Pavillon des orphelines", "Joanna Goodman", ["Historique", "Canada", "Drame", "Famille"]],
    ["L'aile des vierges", "Laurence Peyrin", ["Historique", "Romance", "France", "19e siècle"]],
    ["My Absolute Darling", "Gabriel Tallent", ["Thriller", "Psychologique", "Coming-of-age", "Survie"]],
    ["Tu me manques", "Harlan Coben", ["Thriller", "Suspense", "Mystère", "Crime"]],
    ["Le Tueur aveugle", "Margaret Atwood", ["Roman", "Dystopie", "Science-fiction", "Féministe"]],
    ["Les Sept Morts d'Evelyn Hardcastle", "Stuart Turton", ["Mystère", "Science-fiction", "Thriller", "Énigme"]],
    ["Les meufs c'est des mecs bien", "Mourad Winter", ["Humour", "Essai", "Société", "Stand-up"]],
    ["Marques de fabrique", "Cecile Baudin", ["Roman", "Terroir", "France", "Social"]],
    ["Juliette et les Cézanne", "Jean d'Aillon", ["Historique", "Mystère", "Art", "France"]],
    ["Nos pères, nos frères, nos amis", "Mathieu Palain", ["Documentaire", "Société", "Violence", "Masculinité"]],
    ["Seule en sa demeure", "Cécile Coulon", ["Roman", "Noir", "Rural", "Gothique"]],
    ["The Fuck-Up", "Arthur Nersesian", ["Roman", "Urban", "New York", "Coming-of-age"]],
    ["The Da Vinci Code", "Dan Brown", ["Thriller", "Mystère", "Ésotérique", "Aventure"]],
    ["Les Promises", "Jean-Christophe Grangé", ["Thriller", "Polar", "Mystère", "Suspense"]],
    ["Poirot Halloween", "Agatha Christie", ["Mystère", "Policier", "Classique", "Whodunit"]],
    ["Au NON des femmes", "Jennifer Tamas", ["Essai", "Féminisme", "Littérature", "Critique"]],
    ["Le Silence des vaincues", "Pat Barker", ["Historique", "Guerre", "Mythologie", "Féministe"]],
    ["Le Maître du Haut Château", "Philip K. Dick", ["Science-fiction", "Uchronie", "Dystopie", "Alternatif"]],
    ["Le roi transparent", "Rosa Montero", ["Fantasy", "Historique", "Médiéval", "Féministe"]],
    ["Ne tirez pas sur l'oiseau moqueur", "Harper Lee", ["Classique", "Drame", "Justice", "Américain"]],
    ["Je crois que j'ai tué ma femme", "Frasse Mikardsson", ["Thriller", "Noir", "Psychologique", "Suédois"]],
    ["Les hommes ont peur de la lumière", "Douglas Kennedy", ["Roman", "Psychologique", "Contemporain", "Drame"]],
    ["Artemisia", "Alexandra Lapierre", ["Biographie romancée", "Art", "Renaissance", "Féministe"]],
    ["Humus", "Gaspard Kœnig", ["Roman", "Philosophique", "Écologie", "Politique"]],
    ["La Mariée portait des bottes jaunes", "Katherine Pancol", ["Romance", "Contemporain", "Humour", "Feel-good"]],
    ["Les voleurs d'innocence", "Sarai Walker", ["Roman", "Féministe", "Thriller", "Social"]],
    ["Le Portrait de mariage", "Maggie O'Farrell", ["Historique", "Art", "Renaissance", "Biographique"]],
    ["L'École aux oiseaux", "Clare Beams", ["Roman", "Gothique", "Historique", "Mystère"]],
    ["La Collectionneuse des mots oubliés", "Pip Williams", ["Historique", "Féministe", "Linguistique", "Victorien"]],
    ["Eon et le douzième dragon", "Alison Goodman", ["Fantasy", "Young Adult", "Dragons", "Asiatique"]],
    ["Les Fiancés de l'hiver", "Christelle Dabos", ["Fantasy", "Young Adult", "Steampunk", "Romance"]],
    ["The Calling", "James Frey", ["Young Adult", "Science-fiction", "Dystopie", "Aventure"]],
    ["Chapterhouse: Dune", "Frank Herbert", ["Science-fiction", "Space Opera", "Épique", "Philosophique"]],
    ["Heretics of Dune", "Frank Herbert", ["Science-fiction", "Space Opera", "Épique", "Philosophique"]],
    ["God Emperor of Dune", "Frank Herbert", ["Science-fiction", "Space Opera", "Épique", "Philosophique"]],
];

$stmt = $pdo->prepare('INSERT INTO books (title, author, genres) VALUES (?, ?, ?)');

$inserted = 0;
foreach ($books as $book) {
    $stmt->execute([$book[0], $book[1], json_encode($book[2])]);
    $inserted++;
}

echo json_encode(['success' => true, 'inserted' => $inserted]);
